Pages/Developer.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WeatherApp.Pages
{
    public class Developer : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using Newtonsoft.Json.Linq;

namespace WeatherApp.Pages
{
    public class IndexModel : PageModel
    {
        // URL where i call the API
        private string _url = "http://api.weatherapi.com/v1/current.json?key=";
        //Information class about the weather
        public Information Info { get; private init; }
        //Location class about the weather
        public Location Location { get; private set; }
        
        //String where's the response JSON sent by API
        private string _result = "";

        public IndexModel()
        {
            Info = new Information();
            string key;
            
            /*
             * Take the API key:
             *  - If there's the file (localhost) it take the key from the file
             *  - If there isn't the file (Server) it the the key from Environment variable
             */
            try
            {
                var read = new StreamReader("API.txt");
                key = read.ReadLine();
            }
            catch (Exception)
            {
                key = Environment.GetEnvironmentVariable("ApiKey");
            }

            _url += key;
        }
        
        public async Task OnPostSearch(string city)
        {
            //Call the API and take the JSON
            using (var req = new HttpClient())
            {
                _url += $"&q={city}&aqi=no";
                try
                {
                    _result = await req.GetStringAsync(_url);
                }
                catch (HttpRequestException)
                {
                    Info.Text = "Please insert a valid city";
                    return;
                }
                catch (Exception)
                {
                    Info.Text = "Error!";
                    return;
                }
            }

            //Deserializing JSON and taking the information that are stored in the class
            var deserialized = JObject.Parse(_result);
            try
            {
                Info.TempC = deserialized["current"]?["temp_c"]?.ToObject<double>();
                Info.Text = deserialized["current"]?["condition"]?["text"]?.ToString();
                Info.Icon = deserialized["current"]?["condition"]?["icon"]?.ToString();
                Location = deserialized["location"]?.ToObject<Location>();
            }
            catch (NullReferenceException)
            {
                RedirectToPage("Index");
            }
            catch (InvalidOperationException)
            {
                RedirectToPage("Index");
            }
        }
    }

    //Class information where there's the weather information
    public class Information
    {
        public string Text { get; set; }
        public string Icon { get; set; }
        public double? TempC { get; set; }
    }

    //Class location where there's the location chosen by the user
    public class Location
    {
        public Location(string name, string region, string country)
        {
            Name = name;
            Region = region;
            Country = country;
        }

        private string Name { get; set; }
        private string Region { get; set; }
        private string Country { get; set; }

        public override string ToString()
        {
            return $"{Name}, {Region}, {Country}";
        }
    }
}

Pages/Developer.cshtml
@page
@model WeatherApp.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Developer</title>
    <link rel="stylesheet" href="Style/document.css"/>
</head>
<body>
<div class="wrap">
    <header>
        <div class="button">
            <img src="Image/menu.png" alt="menu image" onclick="anim()"/>
        </div>
        
        <nav class="nav">
            <ul>
                <li>
                    <hr>
                    <a href="#language">
                        Language
                    </a>
                    <hr>
                </li>
                <li>
                    <a href="#contribute">
                        Contribute
                    </a>
                    <hr>
                </li>
                <li>
                    <a href="#structure">
                        Structure
                    </a>
                    <hr>
                </li>
                <li>
                    <a href="#requirements">
                        Requirements
                    </a>
                    <hr>
                </li>
            </ul>
        </nav>
    </header>

    <main>
        <section id="language">
            <h2>These are the language and technologies used in the site</h2>
            <ul>
                <li>HTML</li>
                <li>CSS</li>
                <li>JS</li>
                <li>C#</li>
                <li>ASP.NET Core</li>
                <li>JSON</li>
            </ul>
        </section>

        <section id="contribute">
            <h2>How to contribute?</h2>
            <p>
                If you want to contribute to the project please send me a pull request on the official repo of the project
                <a href="https://www.github.com/ImAl3x03/WeatherApp" target="_blank">at this link</a>
            </p>

            <p>
                If you want to get the complete access to the repository please text me on
                <a href="https://w.me/im_al3x" target="_blank">Telegram</a>
                with all the modify that you want to add to the project
            </p>

            <p>
                <span>I can remove the access to the repo whenever i want</span>
            </p>
        </section>

        <section id="structure">
            <h2>Project structure</h2>
            <p>
                The project has the following structure:
            </p>
            <ul>
                <li>
                    <h3>Properties</h3>
                    <p>All the file with the properties to start the project</p>
                </li>
                <li>
                    <h3>Pages</h3>
                    <p>
                        All the pages of the project
                    </p>
                </li>
                <li>
                    <h3>wwwroot</h3>
                    <ul>
                        <li>
                            <h4>Image</h4>
                            <p>
                                All the image used in the website
                            </p>
                            <ul>
                                <li>
                                    <h5>Footer</h5>
                                    <p>All the image used in the footer</p>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <h4>JavaScript</h4>
                            <p>All the JavaScript script</p>
                        </li>
                        <li>
                            <h4>Style</h4>
                            <p>The style file of the page</p>
                        </li>
                    </ul>
                </li>
            </ul>
        </section>
        
        <section id="requirements">
            <h2>Requirement</h2>
            <p>To use the project you need:</p>
            <ol>
                <li>
                    A browser
                </li>
                <li>
                    <a href="https://dotnet.microsoft.com/download" target="_blank">
                        .NET Compiler
                    </a>
                    <p>
                        If you want to use an IDE i recommended you to use
                        <a href="https://www.visualstudio.microsoft.com/it/downloads" target="_blank">
                            VisualStudio
                        </a>
                        or
                        <a href="https://www.jetbrains.com/rider" target="_blank">
                            Rider
                        </a>
                    </p>
                </li>
                <li>
                    <p>
                        You must need an API Key provided by
                        <a href="https://weatherapi.com/" target="_blank">
                            Weather API.
                        </a>
                        The API Key must be in a file names 'API.txt' in the project root folder.
                    </p>
                </li>
            </ol>
        </section>
    </main>
</div>

<footer>
    <div class="link">
        <a href="https://www.github.com/ImAl3x03/WeatherApp" target="_blank">
            <img src="Image/Footer/GitHub.png" alt="GitHub logo"/>
        </a>

        <a href="https://www.linkedin.com/in/alessandro-di-maria03" target="_blank">
            <img src="Image/Footer/linkedin.png" alt="LinkedIn logo"/>
        </a>

        <a href="https://t.me/im_al3x" target="_blank">
            <img src="Image/Footer/telegram.png" alt="Telegram logo"/>
        </a>

        <p>
            <a style="text-decoration: underline;" asp-page="Index">Back home</a>
        </p>
    </div>

    <div class="credit">
        <p>&copy; Alessandro Di Maria, 2021</p>
        <p>
            <span>BSD-2 License</span>
        </p>
    </div>
</footer>

<script src="JavaScript/nav.js"></script>

</body>
</html>

Pages/Index.cshtml
@page
@model WeatherApp.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Weather</title>
    <link rel="stylesheet" href="Style/style.css"/>
</head>
<body>
<nav class="navbar">
    <div class="form">
        <form method="post">
            <div class="form-row">
                <label for="search">Search your city</label>
            </div>
            <div class="form-row">
                <input type="text" name="city" id="search"/>
                <input type="submit" asp-page-handler="Search" value="Search"/>
            </div>
        </form>
    </div>
    <div class="time">
        <p id="time"></p>
    </div>
</nav>

<main>
    <!-- Empty div to take space from navbar -->
    <div class="space"></div>

    <!-- User's city choose -->
    @if (@Model.Location != null)
    {
        <h1>@Model.Location.ToString()</h1>
    }

    <!-- Show the date that i take from the JSON -->
    @if (@Model.Info != null)
    {
        <div class="weather">
            <img src="@Url.Content(@Model.Info.Icon)" alt="Weather image" class="hide"/>
            <p>@Model.Info.Text</p>
        </div>

        <div class="temperature">
            <img src="Image/temperature.png" alt="Temperature image" class="hide"/>
            <p>@Model.Info.TempC</p>
        </div>
    }
</main>

<footer>
    <div class="link">
        <a href="https://www.github.com/ImAl3x03/WeatherApp" target="_blank">
            <img src="Image/Footer/GitHub.png" alt="GitHub logo"/>
        </a>

        <a href="https://www.linkedin.com/in/alessandro-di-maria03" target="_blank">
            <img src="Image/Footer/linkedin.png" alt="LinkedIn logo"/>
        </a>
        
        <a href="https://t.me/im_al3x" target="_blank">
            <img src="Image/Footer/telegram.png" alt="Telegram logo"/>
        </a>
        
        <p><a style="text-decoration: underline;" asp-page="Developer">Are you developer?</a></p>
    </div>

    <div class="credit">
        <p>&copy; Alessandro Di Maria, 2021</p>
        <p>
            <span>BSD-2 License</span>
        </p>
    </div>
</footer>

<script src="JavaScript/time.js"></script>
<script src="JavaScript/image.js"></script>
</body>
</html>